-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'DELIVERY_MAN', 'SUPER_ADMIN');

-- CreateEnum
CREATE TYPE "DeliveryState" AS ENUM ('AJOUTE', 'ANNULE', 'ANNULE_PAS_INTERESSE', 'ANNULE_SUIVI', 'CHANGE', 'CHANGEMENT_CLIENT', 'CHANGEMENT_NUMERO', 'DEMANDE_DE_RETOUR', 'EXPEDIE', 'HORS_ZONE', 'INJOIGNABLE', 'INJOIGNABLE_SUIVI', 'INTERESSE', 'LIVRE', 'MANQUE_DE_STOCK', 'MISE_EN_DISTRIBUTION', 'NUMERO_ERRONE', 'NUMERO_INCORRECT', 'PAS_DE_REPONSE', 'PAS_DE_REPONSE_SUIVI', 'PAS_DE_REPONSE_2', 'PAS_DE_REPONSE_3', 'PAS_DE_REPONSE_4', 'PAS_DE_REPONSE_5', 'PAS_DE_REPONSE_LV', 'PRET_POUR_EXPEDITION', 'PROGRAMME', 'RAMASSE', 'RECU_PAR_LIVREUR', 'REFUSE', 'REPORTE', 'REPORTE_SUIVI', 'RETOUR_CLIENT_RECU', 'RETOUR_RECU_AGENCE_CASA', 'RETOURNE', 'RETOURNE_VERS_AGENCE');

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'USER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Delivery" (
    "id" SERIAL NOT NULL,
    "clientName" TEXT NOT NULL,
    "serialNumber" TEXT,
    "price" DOUBLE PRECISION,
    "address" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "state" "DeliveryState" NOT NULL DEFAULT 'AJOUTE',
    "assignedToId" INTEGER,
    "createdById" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Delivery_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
